# Generated by Django 4.2.5 on 2023-10-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveIntegerField(),
        ),
    ]
