# Generated by Django 4.2.5 on 2023-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0005_alter_dish_name_alter_dish_price_alter_dishtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
